NumControllers: 4
Controller1:
 controller_name: "stop"
 kp: 0
 ki: 0
 kd: 0
 numInputs: 0
Controller2:
 controller_name: "gotoAngle"
 kp: 1
 ki: 0
 kd: 0
 numInputs: 2
 input1: 0.1 #m/s user define input
 input2: 45 #degree
Controller3:
 controller_name: "gotoGoal"
 kp: 1
 ki: 0.01
 kd: 0.01
 numInputs: 4
 input1: 0.1 #m/s
 input2: 0.3 #m x coordinate
 input3: 0.3 #m y coordinate
 input4: 0.02 #d_stop 2cm
Controller4:
 controller_name: "avoidObstacles"
 kp: 8
 ki: 0.1
 kd: 0.5
 numInputs: 1
 input1: 0.07 #m/s
